version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
  target-branch: "master"
  assignees:
    - "jsmon"
  reviewers:
    - "jsmon"
  open-pull-requests-limit: 10
